/**
 * Fidelity tests: the TS engine must reproduce the Python assembler's
 * encodings and the Verilator simulator's run results exactly. Golden
 * vectors are generated by scripts/gen_golden.py.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { assemble, toHex } from './asm';
import { VM, Memory } from './vm';
import { verify, defaultManifest } from './verifier';
import { compileC } from './cc';
import golden from './golden.json';

const HERE = dirname(fileURLToPath(import.meta.url));
const OPDIR = join(HERE, '../data/operators');
const EXDIR = join(HERE, '../data/examples');

function opSource(name: string): string {
  return readFileSync(join(OPDIR, `${name}.tasm`), 'utf8');
}

const OPERATOR_NAMES = ['graph_walk', 'page_table_walk', 'dist_lock', 'moe_expert', 'paged_attention'];

describe('assembler encodings match Python reference', () => {
  for (const name of OPERATOR_NAMES) {
    it(`encodes ${name} identically`, () => {
      const prog = assemble(opSource(name), name);
      const hex = prog.words.map((w) => w.toString(16).padStart(16, '0'));
      expect(hex).toEqual((golden.encodings as Record<string, string[]>)[name]);
    });
  }

  for (const run of golden.runs as any[]) {
    if (!run.src) continue;
    it(`encodes inline program ${run.name} identically`, () => {
      const prog = assemble(run.src, run.name);
      const hex = prog.words.map((w) => w.toString(16).padStart(16, '0'));
      expect(hex).toEqual((golden.encodings as Record<string, string[]>)[run.name]);
    });
  }
});

describe('VM run results match Verilator reference', () => {
  for (const run of golden.runs as any[]) {
    it(`runs ${run.name} to the same r0..r3`, () => {
      const src = run.src ?? opSource(run.op);
      const prog = assemble(src, run.name);
      const mem = new Memory();
      if (run.dma) mem.seedWords((run.dma as number[]).map((x) => BigInt(x)));
      const vm = new VM(
        prog,
        (run.args as number[]).map((x) => BigInt(x)),
        mem,
      );
      const res = vm.run();
      const hex = res.result.map((w) => w.toString(16).padStart(16, '0'));
      expect(hex).toEqual(run.expect.regs);
      expect(res.err).toBe(run.expect.err);
    });
  }
});

describe('latency model tracks the prototype for indirection-bound operators', () => {
  // graph_walk is LOAD-dominated; our cost model reproduces it closely.
  for (const run of (golden.runs as any[]).filter((r) => /^graph_walk_d/.test(r.name))) {
    it(`${run.name} cycles within tolerance of RTL`, () => {
      const prog = assemble(opSource('graph_walk'), 'graph_walk');
      const mem = new Memory();
      mem.seedWords((run.dma as number[]).map((x) => BigInt(x)));
      const vm = new VM(prog, (run.args as number[]).map((x) => BigInt(x)), mem);
      const res = vm.run();
      const rtl = run.expect.cycles as number;
      expect(Math.abs(res.cycles - rtl) / rtl).toBeLessThan(0.05);
    });
  }
});

describe('verifier accepts the shipped operators', () => {
  for (const name of OPERATOR_NAMES) {
    it(`verifies ${name} with a permissive manifest`, () => {
      const prog = assemble(opSource(name), name);
      const rep = verify(prog, defaultManifest(name));
      // shipped operators are well-formed; permissive manifest -> ok
      expect(rep.nInstructions).toBeGreaterThan(0);
      expect(rep.staticStepBound).toBeGreaterThan(0);
    });
  }

  it('rejects an opaque LOAD used as an address without ANDI', () => {
    const prog = assemble('LOAD r2, [r1 + 0]\nLOAD r3, [r2 + 0]\nADDI r1, r3, 0\nRET r1', 'bad');
    const rep = verify(prog, defaultManifest('bad'));
    expect(rep.ok).toBe(false);
    expect(rep.issues.join(' ')).toMatch(/opaque/);
  });
});

describe('C compiler lowers example sources to runnable .tasm', () => {
  it('compiles graph_walk.c and reproduces the pointer chase', () => {
    const src = readFileSync(join(EXDIR, 'graph_walk.c'), 'utf8');
    const { tasm } = compileC(src);
    const prog = assemble(tasm, 'graph_walk_c');
    // Build a 4-node linked list: node i at byte 16*i, next at +8.
    const mem = new Memory();
    const words: bigint[] = [];
    for (let i = 0; i < 6; i++) {
      words.push(BigInt(0xdec0de00 + i));
      words.push(BigInt(i + 1 < 6 ? (i + 1) * 16 : 0));
    }
    mem.seedWords(words);
    const vm = new VM(prog, [0n, 3n], mem);
    const res = vm.run();
    expect(res.result[0]).toBe(BigInt(0xdec0de03)); // data of node at depth 3
    expect(res.err).toBe(false);
  });

  it('compiles atomic_inc.c', () => {
    const src = readFileSync(join(EXDIR, 'atomic_inc.c'), 'utf8');
    const { tasm } = compileC(src);
    const prog = assemble(tasm, 'atomic_inc');
    const mem = new Memory();
    mem.store64(0n, 100n);
    const vm = new VM(prog, [0n, 5n], mem);
    const res = vm.run();
    expect(res.result[0]).toBe(100n); // returns old value
    expect(mem.load64(0n)).toBe(105n); // incremented
  });
});
