[operator]
name        = "dist_lock"
version     = 1
max_dynamic = 2048

[[arguments]]
name   = "latch"
reg    = 1
bounds = [0, 0xFFFF]
device = 0
region = 0

[[arguments]]
name   = "state"
reg    = 2
bounds = [0, 0xFFFF]
device = 0
region = 0

[[arguments]]
name   = "newVal"
reg    = 3
bounds = [0, 0xFFFFFFFFFFFFFFFF]

[[arguments]]
name   = "rep1"
reg    = 4
bounds = [0, 0xFFFFFFFFFFFFFFFF]

[[arguments]]
name   = "rep2"
reg    = 5
bounds = [0, 0xFFFFFFFFFFFFFFFF]

[[arguments]]
name   = "retries"
reg    = 6
bounds = [0, 64]

[[regions]]
id     = 0
device = 0
name   = "lock_state"
size   = 0x100000
