[operator]
name        = "paged_attention"
version     = 1
max_dynamic = 131072

[[arguments]]
name   = "btbase"
reg    = 1
bounds = [0, 0x7FFFFFF8]
device = 0
region = 1

[[arguments]]
name   = "nblock"
reg    = 2
bounds = [0, 16384]

[[arguments]]
name   = "bsize"
reg    = 3
bounds = [0, 0x100000]

[[arguments]]
name   = "dst"
reg    = 4
bounds = [0, 0x7FFFFFF8]
device = 0
region = 0

[[regions]]
id     = 0
device = 0
name   = "client_recv_buffer"
size   = 0x80000000

[[regions]]
id     = 1
device = 0
name   = "block_table"
size   = 0x80000000
