[operator]
name        = "page_table_walk"
version     = 1
max_dynamic = 256

[[arguments]]
name   = "vaddr"
reg    = 1
bounds = [0, 0xFFFFFFFFFFFF]

[[arguments]]
name   = "l1"
reg    = 2
bounds = [0, 0x10000000]
device = 0
region = 1

[[arguments]]
name   = "dst"
reg    = 3
bounds = [0, 0x10000000]
device = 0
region = 0

[[regions]]
id     = 0
device = 0
name   = "client_recv_buffer"
size   = 0x80000000

[[regions]]
id     = 1
device = 0
name   = "page_tables"
size   = 0x20000000
