// AUTO-GENERATED by scripts/gen_isa_pkg.py — do not edit by hand.
// Source: sw/asm/tiara_isa.py
// Run `python3 scripts/gen_isa_pkg.py` to regenerate after ISA changes.

`ifndef TIARA_PKG_SVH
`define TIARA_PKG_SVH

package tiara_pkg;

  // Architectural constants ------------------------------------------------
  localparam int unsigned NUM_REGS              = 16;
  localparam int unsigned NUM_REG_IDX_BITS      = 4;
  localparam int unsigned INSTR_STORE_DEPTH     = 1024;
  localparam int unsigned INSTR_BYTES           = 8;
  localparam int unsigned INSTR_WIDTH           = INSTR_BYTES * 8;
  localparam int unsigned MAX_LOOP_NEST         = 8;
  localparam int unsigned MAX_INFLIGHT_PER_TASK = 32;
  localparam int unsigned DEFAULT_MAX_DYNAMIC   = 4096;

  // Address layout ---------------------------------------------------------
  localparam int unsigned ADDR_DEVICE_BITS = 16;
  localparam int unsigned ADDR_REGION_BITS = 16;
  localparam int unsigned ADDR_OFFSET_BITS = 32;

  // Opcodes --------------------------------------------------------------
  localparam logic [7:0] OP_NOP     = 8'h00;
  localparam logic [7:0] OP_LOAD    = 8'h01;
  localparam logic [7:0] OP_STORE   = 8'h02;
  localparam logic [7:0] OP_JUMP    = 8'h10;
  localparam logic [7:0] OP_LOOP    = 8'h11;
  localparam logic [7:0] OP_WAIT    = 8'h12;
  localparam logic [7:0] OP_RET     = 8'h13;
  localparam logic [7:0] OP_COMPUTE = 8'h20;
  localparam logic [7:0] OP_MEMCPY  = 8'h83;
  localparam logic [7:0] OP_CAS     = 8'h84;
  localparam logic [7:0] OP_CAA     = 8'h85;

  // COMPUTE sub-opcodes --------------------------------------------------
  localparam logic [3:0] SUB_ADD  = 4'h0;
  localparam logic [3:0] SUB_SUB  = 4'h1;
  localparam logic [3:0] SUB_AND  = 4'h2;
  localparam logic [3:0] SUB_OR   = 4'h3;
  localparam logic [3:0] SUB_XOR  = 4'h4;
  localparam logic [3:0] SUB_SHL  = 4'h5;
  localparam logic [3:0] SUB_SHR  = 4'h6;
  localparam logic [3:0] SUB_MUL  = 4'h7;
  localparam logic [3:0] SUB_ADDI = 4'h8;
  localparam logic [3:0] SUB_ANDI = 4'h9;
  localparam logic [3:0] SUB_SHLI = 4'hA;
  localparam logic [3:0] SUB_SHRI = 4'hB;
  localparam logic [3:0] SUB_LI   = 4'hC;
  localparam logic [3:0] SUB_EQ   = 4'hD;
  localparam logic [3:0] SUB_LT   = 4'hE;
  localparam logic [3:0] SUB_GE   = 4'hF;

  // MEMCPY flag bits -----------------------------------------------------
  localparam logic [3:0] MEMCPY_FLAG_ASYNC          = 4'h1;
  localparam logic [3:0] MEMCPY_FLAG_LEN_FROM_REG   = 4'h2;
  localparam logic [3:0] MEMCPY_FLAG_STRIDED_GATHER = 4'h4;
  localparam logic [3:0] MEMCPY_FLAG_STRIDED_SCAT   = 4'h8;

  // Field positions in the 64-bit instruction word ----------------------
  localparam int OP_LO  = 56;
  localparam int RD_LO  = 52;
  localparam int RS1_LO = 48;
  localparam int RS2_LO = 44;
  localparam int SUB_LO = 40;
  localparam int IMM_LO = 0;
  localparam int IMM_W  = 40;

  // Two-word opcode bit (top bit of OP byte set) ------------------------
  function automatic logic op_is_two_word(input logic [7:0] op);
    op_is_two_word = op[7];
  endfunction

endpackage : tiara_pkg

`endif
