#!/usr/bin/env python3
"""Generate `rtl/include/tiara_pkg.svh` from `sw/asm/tiara_isa.py`.

Keeps RTL opcode/register/limit constants byte-identical to the
assembler's view.  Run:

    python3 scripts/gen_isa_pkg.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "sw" / "asm"))

from tiara_isa import (  # noqa: E402
    ADDR_DEVICE_BITS,
    ADDR_OFFSET_BITS,
    ADDR_REGION_BITS,
    DEFAULT_MAX_DYNAMIC,
    INSTR_BYTES,
    INSTR_STORE_DEPTH,
    MAX_INFLIGHT_PER_TASK,
    MAX_LOOP_NEST,
    MEMCPY_FLAG_ASYNC,
    MEMCPY_FLAG_LEN_FROM_REG,
    MEMCPY_FLAG_STRIDED_GATHER,
    MEMCPY_FLAG_STRIDED_SCAT,
    NUM_REGS,
    Op,
    Sub,
)


HEADER = """// AUTO-GENERATED by scripts/gen_isa_pkg.py — do not edit by hand.
// Source: sw/asm/tiara_isa.py
// Run `python3 scripts/gen_isa_pkg.py` to regenerate after ISA changes.

`ifndef TIARA_PKG_SVH
`define TIARA_PKG_SVH

package tiara_pkg;

  // Architectural constants ------------------------------------------------
  localparam int unsigned NUM_REGS              = %(num_regs)d;
  localparam int unsigned NUM_REG_IDX_BITS      = %(num_reg_bits)d;
  localparam int unsigned INSTR_STORE_DEPTH     = %(istore)d;
  localparam int unsigned INSTR_BYTES           = %(ibytes)d;
  localparam int unsigned INSTR_WIDTH           = INSTR_BYTES * 8;
  localparam int unsigned MAX_LOOP_NEST         = %(loop_nest)d;
  localparam int unsigned MAX_INFLIGHT_PER_TASK = %(inflight)d;
  localparam int unsigned DEFAULT_MAX_DYNAMIC   = %(max_dyn)d;

  // Address layout ---------------------------------------------------------
  localparam int unsigned ADDR_DEVICE_BITS = %(dev)d;
  localparam int unsigned ADDR_REGION_BITS = %(reg)d;
  localparam int unsigned ADDR_OFFSET_BITS = %(off)d;

"""

OPCODE_BLOCK = "  // Opcodes --------------------------------------------------------------\n"
OPCODE_FMT   = "  localparam logic [7:0] OP_%(name)-7s = 8'h%(val)02X;\n"
SUB_BLOCK    = "\n  // COMPUTE sub-opcodes --------------------------------------------------\n"
SUB_FMT      = "  localparam logic [3:0] SUB_%(name)-4s = 4'h%(val)X;\n"

FLAGS_BLOCK = """
  // MEMCPY flag bits -----------------------------------------------------
  localparam logic [3:0] MEMCPY_FLAG_ASYNC          = 4'h%(async)X;
  localparam logic [3:0] MEMCPY_FLAG_LEN_FROM_REG   = 4'h%(lenreg)X;
  localparam logic [3:0] MEMCPY_FLAG_STRIDED_GATHER = 4'h%(gather)X;
  localparam logic [3:0] MEMCPY_FLAG_STRIDED_SCAT   = 4'h%(scat)X;

  // Field positions in the 64-bit instruction word ----------------------
  localparam int OP_LO  = 56;
  localparam int RD_LO  = 52;
  localparam int RS1_LO = 48;
  localparam int RS2_LO = 44;
  localparam int SUB_LO = 40;
  localparam int IMM_LO = 0;
  localparam int IMM_W  = 40;

  // Two-word opcode bit (top bit of OP byte set) ------------------------
  function automatic logic op_is_two_word(input logic [7:0] op);
    op_is_two_word = op[7];
  endfunction

endpackage : tiara_pkg

`endif
"""


def main() -> int:
    out = ROOT / "rtl" / "include" / "tiara_pkg.svh"
    body = HEADER % dict(
        num_regs=NUM_REGS,
        num_reg_bits=(NUM_REGS - 1).bit_length(),
        istore=INSTR_STORE_DEPTH,
        ibytes=INSTR_BYTES,
        loop_nest=MAX_LOOP_NEST,
        inflight=MAX_INFLIGHT_PER_TASK,
        max_dyn=DEFAULT_MAX_DYNAMIC,
        dev=ADDR_DEVICE_BITS,
        reg=ADDR_REGION_BITS,
        off=ADDR_OFFSET_BITS,
    )
    body += OPCODE_BLOCK
    for op in sorted(Op, key=lambda o: int(o)):
        body += OPCODE_FMT % {"name": op.name, "val": int(op)}
    body += SUB_BLOCK
    for s in sorted(Sub, key=lambda x: int(x)):
        body += SUB_FMT % {"name": s.name, "val": int(s)}
    body += FLAGS_BLOCK % {
        "async":  MEMCPY_FLAG_ASYNC,
        "lenreg": MEMCPY_FLAG_LEN_FROM_REG,
        "gather": MEMCPY_FLAG_STRIDED_GATHER,
        "scat":   MEMCPY_FLAG_STRIDED_SCAT,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
